### ISSUE TITLE
[1.17.1] applied energistics Rendering issue on server

### ISSUE THREAD

**Issue by MSandro** [comp500/Indium#107]
```
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: net.minecraft.class_148: Tesselating block in world - Indium Renderer
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:85)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$end000$onRenderBlock(ChunkRenderRebuildTask.java:561)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:254)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:294)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "appeng.blockentity.crafting.CraftingCubeModelData.getForward()" because "modelData" is null
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at appeng.client.render.crafting.MonitorBakedModel.addInnerCube(MonitorBakedModel.java:62)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at appeng.client.render.crafting.CraftingCubeBakedModel.emitBlockQuads(CraftingCubeBakedModel.java:117)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at appeng.client.render.crafting.MonitorBakedModel.emitBlockQuads(MonitorBakedModel.java:36)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:80)
[08:45:42] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	... 5 more
```
![image](https://user-images.githubusercontent.com/10937159/158127448-d6cda4c1-e973-4c73-a75f-fa879e77c4d6.png)
if I leave my base (chunks unloaded)
and I travel back, the chunk where I have placed the ME-Controller is not rendering correctly.
I hope someon could help.

sodium-fabric-mc1.17.1-0.3.4+build.13
indium-1.0.1+mc1.17.1

**Comment by comp500** [comment]
(from linked issue: not an Indium issue, related to Iris)
