### ISSUE TITLE
Indium 1.0.4+mc1.19  java.lang.IllegalArgumentException: wrong number of arguments

### ISSUE THREAD

**Issue by DadoIrie** [comp500/Indium#124]
mods loaded (with PolyMC 1.3.1): Fabric API 0.55.2+1.19, Sodium 0.4.2+build.16, Indium 1.0.4+mc1.19

launching minecraft works, but this error shows up

java.lang.IllegalArgumentException: wrong number of arguments
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at link.infra.indium.renderer.aocalc.VanillaAoHelper$1.get(VanillaAoHelper.java:55) [indium-1.0.4+mc1.19.jar:?]
	at link.infra.indium.renderer.aocalc.VanillaAoHelper$1.get(VanillaAoHelper.java:51) [indium-1.0.4+mc1.19.jar:?]
	at link.infra.indium.renderer.aocalc.VanillaAoHelper.initialize(VanillaAoHelper.java:66) [indium-1.0.4+mc1.19.jar:?]
	at net.minecraft.class_778.handler$zii000$onInit(class_778.java:566) [client-intermediary.jar:?]
	at net.minecraft.class_778.<init>(class_778.java:40) [client-intermediary.jar:?]
	at net.minecraft.class_776.<init>(class_776.java:39) [client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:557) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:198) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.7.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:127) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:57) [NewLaunch.jar:?]

Full log uploaded:
https://mclo.gs/5IKebix

**Comment by comp500** [comment]
Hmm, looks like this was fixed in Indigo with https://github.com/FabricMC/fabric/commit/56447d9b95f88da22dab4904831ed013e55ee390; I'll see if I can port over the change... not sure if the change to AWs was for performance or just to reduce the amount of code?

**Comment by DadoIrie** [comment]
I'm not a modder and therefore no idea what's the question. Just wanted to share this and seems like you already know what's the cause ;) do I need to do anything on my side or simply wait for an update?

**Comment by comp500** [comment]
I've managed to replicate the issue, thanks for reporting it!

**Comment by DadoIrie** [comment]
still haven't figured out what might be not working with this error ... what does it mean?

**Comment by breadbyte** [comment]
It's an issue with Indium itself that requires an update.

**Comment by comp500** [comment]
This error doesn't actually cause any problems with the default Indium configuration, and it's very rare to ever need to change the configuration. I'm still going to patch it anyway :P
