### ISSUE TITLE
Seemingly random crashes 

### ISSUE THREAD

**Issue by ghost** [comp500/Indium#148]
[crash-2022-11-12_14.50.38-client.txt](https://github.com/comp500/Indium/files/9995155/crash-2022-11-12_14.50.38-client.txt)

Im getting the error "net.minecraft.class_148: Tessellating block in world - Indium Renderer" to which i saw another person experienced, but as far as i can tell, his issue was fixed in the later releases of fabric-api. I have the latest version of fabric api for 1.19.2 but this still happens

**Comment by comp500** [comment]
Could you send your latest.log file? Also test if this occurs without Sodium or Indium.

**Comment by ghost** [comment]
[2022-11-12-1.log](https://github.com/comp500/Indium/files/9995668/2022-11-12-1.log)
Heres the log file for when it crashed. I dont think i can test without sodium and indium due to the crashes being very infrequent. I played for several hours today with none.

**Comment by comp500** [comment]
I don't think that's the right log, try a slightly newer one? It should have "Tessellating block in world - Indium Renderer" in the log as well.

**Comment by ghost** [comment]
[2022-11-12-2.log](https://github.com/comp500/Indium/files/9995880/2022-11-12-2.log)
My bad, this should be the correct one

**Comment by comp500** [comment]
Try disabling C2ME? If the crashes still occur, try disabling LambdaBetterGrass.

**Comment by comp500** [comment]
Had another look at it: this might be a conflict between Ambient Environment and Better Biome Blend - try disabling one or both of those:
```
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Optional.orElseGet(java.util.function.Supplier)" because the return value of "net.minecraft.class_1959.redirect$gog000$getSeasonGrassColor(net.minecraft.class_4763)" is null
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at net.minecraft.class_1959.method_8711(class_1959.java:274)
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at com.blamejared.ambientenvironment.AmbientEnvironmentCommon.modifyColour(AmbientEnvironmentCommon.java:41)
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at com.blamejared.ambientenvironment.AmbientEnvironmentCommon.lambda$static$0(AmbientEnvironmentCommon.java:24)
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at fionathemortal.betterbiomeblend.sodium.SodiumColorBlending.gatherRawColorsToCaches(SodiumColorBlending.java:148)
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at fionathemortal.betterbiomeblend.sodium.SodiumColorBlending.generateBlendedColorChunk(SodiumColorBlending.java:353)
[14:44:15] [Chunk Render Task Executor #2/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.world.biome.BlockColorCache.getColor(BlockColorCache.java:567)
```

**Comment by phantomhiveing** [comment]
im getting crashes with the same error. my latest.log is attached. first time using github, not sure if i should start a new issue thread. i noticed i had a warning that i needed modmenu so i got that now. i dont think thats what caused the error but we'll see. i dont have LambdaBetterGrass or C2ME.
[latest.log](https://github.com/comp500/Indium/files/11671403/latest.log)

**Comment by comp500** [comment]
@phantomhiveing See https://github.com/comp500/Indium/issues/199

**Comment by comp500** [comment]
Closing: old issue with insufficient information to diagnose
