### ISSUE TITLE
Fatal error "Tessellating block in world" with popular resource pack

### ISSUE THREAD

**Issue by ccyounga** [comp500/Indium#178]
Greetings. Not so long ago, I don’t know from what time exactly, many people began to crash on the game server. Fly after fly in places where there are a lot of buildings, probably, and a lot of difficult blocks.
Crashes happen regularly, when turning the camera or flying over something, chunks stop loading, often you need to restart the server.
Sending the error log: https://hastebin.com/share/rizivakoda.css

This happens when playing with the popular Conquest resource pack, game version 1.18.2. We need this particular resource pack, we used to play well without such crashes with it, but at some point it became the cause of our serious problems.
Any ideas how to help?

**Comment by ccyounga** [comment]
We also tested without shaders, crashes continue: https://hastebin.com/share/ajutirocid.css

**Comment by comp500** [comment]
Could you send the full mod list? There should be one in the crash `.txt` file in the `crash-reports` folder (can just send the whole file). The `latest.log` file in the `logs` folder would also be useful, since it's possible something is going wrong during game startup.

**Comment by ccyounga** [comment]
crash report: https://hastebin.com/share/eqidaxonov.yaml
log: https://dropmefiles.com/VMG9Y

> Could you send the full mod list? There should be one in the crash `.txt` file in the `crash-reports` folder (can just send the whole file). The `latest.log` file in the `logs` folder would also be useful, since it's possible something is going wrong during game startup.

**Comment by comp500** [comment]
I don't think this is an Indium issue... but I did notice the following exception (with several below) printed in your log file:

```
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:61)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$bfa000$onRenderBlock(ChunkRenderRebuildTask.java:554)
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:99)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:273)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:313)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26204()" because the return value of "net.minecraft.class_1920.method_8320(net.minecraft.class_2338)" is null
	at me.pepperbell.continuity.client.processor.simple.RandomSpriteProvider.getSprite(RandomSpriteProvider.java:52)
	at me.pepperbell.continuity.client.processor.simple.SimpleQuadProcessor.processQuad(SimpleQuadProcessor.java:33)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transformOnce(CTMBakedModel.java:110)
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transform(CTMBakedModel.java:89)
	at link.infra.indium.renderer.render.AbstractRenderContext.lambda$new$1(AbstractRenderContext.java:33)
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:42)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.renderQuad(BaseFallbackConsumer.java:101)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:91)
	at link.infra.indium.renderer.render.BaseFallbackConsumer.accept(BaseFallbackConsumer.java:56)
	at net.fabricmc.fabric.api.renderer.v1.render.RenderContext$1.accept(RenderContext.java:62)
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:545)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at dev.lambdaurora.lambdabettergrass.model.LBGLayerBakedModel.emitBlockQuads(LBGLayerBakedModel.java:80)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:57)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:46)
	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:57)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:56)
	... 5 more
```

Try removing Continuity, and see if the issue re-occurs. Also do try removing both Sodium and Indium, since I think the crash might still occur without them. It's possible that a different mod is causing these issues, though I'm not sure which of your mods would be most likely.

**Comment by ccyounga** [comment]
The culprit was the continuity mod, although I wouldn't call it the culprit. Previously, everything worked well, but since recently, how has it suddenly started to fail? That your plugin, that continuity has not been updated since the summer, perhaps the main provocateur is some other mod. I can only guess Sodium Extra and Fabric API.
I have removed the continuity mod from my list for now, but now I have lost the main charm of the resource pack - the connection of textures. This is very sad to realize. Maybe there is some solution or idea?

**Comment by ccyounga** [comment]
Indium cannot be removed for tests, continuity requires it. Sodium, even more so, and there is no point in testing without the main mod, the assembly will not work.

**Comment by comp500** [comment]
Continuity only requires Indium if you are using Sodium - all mods that require Indium with Sodium will work without Sodium, using the Indigo implementation provided in Fabric API. You'll have to remove Reese's Sodium Options, Sodium Shadowy Path Blocks and Sodium Extra; I think everything else will work without Sodium+Indium (so you're only really losing out on performance, not features, if you test without Sodium).

**Comment by ccyounga** [comment]
Nothing helps, the problem is only in the texture connection function of the continuity mod. The only solution is to disable this feature.

**Comment by comp500** [comment]
Ah fair - this issue is not Indium's problem then, please report this to the Continuity dev if they still support 1.18.2.
