### ISSUE TITLE
Minecraft Crash

### ISSUE THREAD

**Issue by KonerDev** [comp500/Indium#180]
When I start Minecraft with Indium I get this error:
![image](https://user-images.githubusercontent.com/105141148/222972677-85137f2c-e2cd-44ea-9e76-ea0421149243.png)

Minecraft 1.19.3 Fabric
My Mods:
```asciidoc
28.02.2023  17:40           136.643 beenfo-1.19.3-fabric0.68.1-1.3.3.jar
02.01.2023  10:05         1.743.279 BetterF3-5.1.0-Fabric-1.19.3.jar
02.01.2023  10:05           172.035 blur-2.6.1.jar
02.01.2023  10:05            43.371 boosted-brightness-2.1.2+1.19.jar
28.02.2023  17:36            14.837 colorfulsubtitles-1.1.0.jar
04.03.2023  20:05         1.145.374 continuity-3.0.0-beta.21.19.3.jar
28.02.2023  17:27            52.177 dark-loading-screen-1.6.13.jar
02.01.2023  10:37            76.646 entityculling-fabric-1.5.2-mc1.19.3.jar
02.01.2023  10:18         1.840.623 fabric-api-0.70.0+1.19.3.jar
02.01.2023  10:13         6.484.318 fabric-language-kotlin-1.9.0+kotlin.1.8.0.jar
02.01.2023  10:05           110.711 FpsReducer2-fabric-1.19.3-2.2.jar
05.03.2023  17:08           113.706 indium-1.0.14+mc1.19.3.jar
05.03.2023  17:07         2.290.376 iris-mc1.19.3-1.5.2.jar
05.03.2023  07:27           559.472 lambdynamiclights-2.2.0+1.19.3.jar
02.01.2023  10:05            14.531 lazydfu-0.1.3.jar
02.01.2023  10:05            66.224 light-overlay-7.0.2-forge.jar
19.02.2023  19:33           903.709 litematica-fabric-1.19.3-0.13.1.jar
02.01.2023  10:37           555.778 lithium-fabric-mc1.19.3-0.10.4.jar
19.02.2023  19:32           514.974 malilib-fabric-1.19.3-0.14.0.jar
02.01.2023  10:05           637.090 modmenu-5.0.2.jar
28.02.2023  17:30            11.223 morechathistory-1.19.1-1.1.1.jar
28.02.2023  17:24         1.204.420 shulkerboxtooltip-fabric-3.2.4+1.19.3.jar
02.01.2023  10:28           264.066 sodium-extra-0.4.16+mc1.19.3-build.91.jar
05.03.2023  17:00           707.249 sodium-fabric-mc1.19.3-0.4.9+build.23.jar
02.01.2023  10:37           127.465 starlight-1.1.1+fabric.ae22326.jar
28.02.2023  18:27             7.042 tnttime-mc1.19.3-1.2.0.jar
28.02.2023  17:25            12.435 tooltipfix-1.1.1-1.19.3.jar
20.02.2023  11:43         5.712.972 worldedit-mod-7.2.13.jar
28.02.2023  17:39           564.257 WorldEditCUI-1.19.3+01.jar
03.03.2023  18:16           804.086 XaerosWorldMap_1.29.1_Fabric_1.19.3.jar
03.03.2023  18:17         1.364.469 Xaeros_Minimap_23.2.0_Fabric_1.19.3.jar
02.01.2023  10:13           214.809 YetAnotherConfigLib-2.2.0.jar
20.02.2023  08:39           629.447 Zoomify-2.9.3.jar
```

crash.txt:
```
Time: 2023-03-05 17:10:19
Description: Initializing game

java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/renderer/v1/render/RenderContext$BakedModelConsumer
	at net.minecraft.class_778.<init>(class_778.java:38)
	at net.minecraft.class_776.<init>(class_776.java:38)
	at net.minecraft.class_310.<init>(class_310.java:577)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.renderer.v1.render.RenderContext$BakedModelConsumer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 8 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_778.<init>(class_778.java:38)
	at net.minecraft.class_776.<init>(class_776.java:38)
	at net.minecraft.class_310.<init>(class_310.java:577)
```

**Comment by InAgony** [comment]
That is the exact issue I have @comp500

**Comment by comp500** [comment]
Update your version of Fabric API.
