### ISSUE TITLE
[1.0.14 for 1.19.3] Fabric Render API version mismatch

### ISSUE THREAD

**Issue by minhperry** [comp500/Indium#183]
On launch the launcher (MultiMC) provided this error:

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 2.1.0+2063beff72 with version 2.1.1 or later.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.14+mc1.19.3 requires version 2.1.1 or later of mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1), but only the wrong version is present: 2.1.0+2063beff72!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:224)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:259)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

```
In the changelog for Sodium 0.4.9 for 1.19.3, the dev also stated that this might break mods that hooks into it, but this update was made almost 2 months ago. Latest Fabric Loader 0.14.18 was also used, but still gives the same error.

**Comment by comp500** [comment]
> `Mod 'Indium' (indium) 1.0.14+mc1.19.3 requires version 2.1.1 or later of mod 'Fabric Renderer API (v1)'`

Update Fabric API to the latest version.
