### ISSUE TITLE
Sides of blocks not rendering

### ISSUE THREAD

**Issue by MarshmallowPeep** [comp500/Indium#201]
I've encountered an issue where the sides of blocks that are not in view aren't rendered with specific texture packs. The ones I saw this with were [Reimagined](https://modrinth.com/resourcepack/reimagined) and [Excalibur](https://www.curseforge.com/minecraft/texture-packs/excalibur). 

![2023-06-15_19 50 50](https://github.com/comp500/Indium/assets/136765173/746cfcbf-fcb7-412f-85ae-4ba32fcc4e02)

-------------------------------------------------------------------------

I'm using Fabric 0.14.21 for 1.19.4

Mods:
Alternate Current
AmbientSounds 5
AutoSwitch [Fabric]
Chat Heads
CleanCut
ClothConfigAPI (Fabric/Forge)
Collective
CreativeCore
Entity Culling Fabric/Forge
Entity Model Features [CEM] [Fabric & Forge]
Entity Texture Features - [Fabric & Forge]
Fabric API
Fabric Language Kotlin
FerriteCore (Fabric)
Indium
Lithium (Fabric)
Mod Menu
Phosphor (Fabric)
Reese's Sodium Options
Sodium
Sodium Extra
Sound Physics Remastered
Xaero's Minimap
Xaero's World Map
Zoomify

**Comment by comp500** [comment]
Looks like you don't have any mod that adds support for the Optifine features these packs use. Try using Continuity?

**Comment by Gentleman2292** [comment]
im also getting the same issue
![image](https://github.com/comp500/Indium/assets/76640636/f13c6cdd-c3a2-4561-b7ba-80fea5738d83)

**Comment by Gentleman2292** [comment]
and this issue too

**Comment by Gentleman2292** [comment]
@comp500 10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:135)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$bkh000$indium$onRenderBlock(ChunkRenderRebuildTask.java:541)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:104)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.processJob(ChunkBuilder.java:286)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:328)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2680.method_26225()" because "$$5" is null
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.minecraft.class_2248.method_9607(class_2248.java:263)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:20)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.CullingCache.shouldCull(CullingCache.java:36)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.EmissiveBakedModel$EmissiveBlockQuadTransform.transform(EmissiveBakedModel.java:133)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:63)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:81)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.AbstractBlockRenderContext$BakedModelConsumerImpl.accept(AbstractBlockRenderContext.java:277)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:63)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:46)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at me.pepperbell.continuity.client.model.EmissiveBakedModel.emitBlockQuads(EmissiveBakedModel.java:63)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:130)
[10:40:16] [Chunk Render Task Executor #0/INFO]: [STDERR]: 	... 5 more

**Comment by Gentleman2292** [comment]
this seems to be in my logs when blocks dont render the sides

**Comment by Gentleman2292** [comment]
![image](https://github.com/comp500/Indium/assets/76640636/95bd525a-5628-4bab-9f93-4e43ea461432)
here is how the game looks like

**Comment by comp500** [comment]
@GentlemanMC You have a different issue, see #199.

@MarshmallowPeep Could you send a log file from when this issue occurs?

**Comment by MarshmallowPeep** [comment]
Since the issue occurred, I loaded a backup of the modpack and that seemed to fix it, but I'll try to recreate it again and I'll send the error log then

**Comment by comp500** [comment]
Closing: old issue with insufficient information to diagnose
