### ISSUE TITLE
Indium requires Fabric Renderer API (v1) version 3.1.0

### ISSUE THREAD

**Issue by TinyDerp** [comp500/Indium#207]
**Indium requires Fabric Renderer API (v1) version 3.1.0** but with the newest Fabric API it's only version 3.0.1.
There are no other incompatibilities with other mods.

Error:
```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 3.0.1+b3afc78b27 and mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1) 3.0.1+b3afc78b77 with mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1), version 3.1.0 or later.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.20+mc1.20.1 requires version 3.1.0 or later of mod 'Fabric Renderer API (v1)' (fabric-renderer-api-v1), but only the wrong versions are present: 3.0.1+b3afc78b27/3.0.1+b3afc78b77!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

```

**Comment by Zubou** [comment]
I have the same problem in my Feather Client gives me the same error

**Comment by Zeycox** [comment]
Same problem, hope someone find a way to fix that soon

**Comment by comp500** [comment]
Which version of Fabric API are you using? 0.84.0 or newer is required.

**Comment by tehbeard** [comment]
> Which version of Fabric API are you using? 0.84.0 or newer is required.

Need to bump Indium's Minecraft version in https://github.com/comp500/Indium/blob/1.20.x/main/src/main/resources/fabric.mod.json up to 1.20.1 then as that's what `Fabric API 0.84.0` requires, and custom launchers aren't going to pickup the dependency tree correctly from curseforge.

**Comment by safder2000** [comment]
> Which version of Fabric API are you using? 0.84.0 or newer is required.

worked👍
