### ISSUE TITLE
Tessellating block in world

### ISSUE THREAD

**Issue by Doc94** [comp500/Indium#245]
I update a few mods in fabric 1.20.1 and get that issue joining.
```
Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at appeng.client.render.model.DriveBakedModel.emitBlockQuads(DriveBakedModel.java:87)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cmm000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103)
```
	
	
[crash-2023-09-25_17.53.06-client.txt](https://github.com/comp500/Indium/files/12719236/crash-2023-09-25_17.53.06-client.txt)

**Comment by comp500** [comment]
You need to update Indium and Sodium.

**Comment by Doc94** [comment]
> You need to update Indium and Sodium.

If update Indium i need update sodium and if update sodium the "Immersive Portals" not start because dont support last sodium versions :/

**Comment by comp500** [comment]
Ah, in that case downgrade Fabric API to version 0.88 until Immersive Portals is compatible with newer Sodium.

**Comment by Doc94** [comment]
> Ah, in that case downgrade Fabric API to version 0.88 until Immersive Portals is compatible with newer Sodium.

I try this and get the same result, maybe need check if another mod updated cause the same error...

**Comment by comp500** [comment]
Could you send the crash log from the crash with Fabric API 0.88.1?

**Comment by comp500** [comment]
Closing (can't replicate issue)
