### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by 3prm3** [comp500/Indium#26]
Reported exception thrown!
net.minecraft.class_148: Rendering overlay
	at net.minecraft.class_757.method_3192(class_757.java:612)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at net.minecraft.class_287.method_1341(class_287.java:1536)
	at net.minecraft.class_1921.method_23012(class_1921.java:596)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
	at net.minecraft.class_4597$class_4598$$Lambda$3258/1269279204.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
	at net.minecraft.class_327.method_27520(class_327.java:109)
	at net.minecraft.class_327.method_1720(class_327.java:58)
	at net.minecraft.class_332.method_25300(class_332.java:114)
	at net.minecraft.class_442.method_25394(class_442.java:260)
	at net.minecraft.class_425.method_25394(class_425.java:75)
	at net.minecraft.class_757.method_3192(class_757.java:605)
	... 10 more

**Comment by 3prm3** [comment]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 2/25/21 7:00 PM
Description: Rendering overlay

java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear()Ljava/nio/ByteBuffer;
	at net.minecraft.class_287.method_1341(class_287.java:1536)
	at net.minecraft.class_1921.method_23012(class_1921.java:596)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
	at net.minecraft.class_4597$class_4598$$Lambda$3258/1269279204.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
	at net.minecraft.class_327.method_27520(class_327.java:109)
	at net.minecraft.class_327.method_1720(class_327.java:58)
	at net.minecraft.class_332.method_25300(class_332.java:114)
	at net.minecraft.class_442.method_25394(class_442.java:260)
	at net.minecraft.class_425.method_25394(class_425.java:75)
	at net.minecraft.class_757.method_3192(class_757.java:605)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_287.method_1341(class_287.java:1536)
	at net.minecraft.class_1921.method_23012(class_1921.java:596)
	at net.minecraft.class_4597$class_4598.method_22994(class_4597.java:86)
	at net.minecraft.class_4597$class_4598.method_24213(class_4597.java:65)
	at net.minecraft.class_4597$class_4598$$Lambda$3258/1269279204.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at net.minecraft.class_4597$class_4598.method_22993(class_4597.java:62)
	at net.minecraft.class_327.method_27520(class_327.java:109)
	at net.minecraft.class_327.method_1720(class_327.java:58)
	at net.minecraft.class_332.method_25300(class_332.java:114)
	at net.minecraft.class_442.method_25394(class_442.java:260)
	at net.minecraft.class_425.method_25394(class_425.java:75)

-- Overlay render details --
Details:
	Overlay name: net.minecraft.class_425
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:605)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2536291344 bytes (2418 MB) / 3355443200 bytes (3200 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		indium: Indium 1.0.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		sodium: Sodium 0.1.1-SNAPSHOT
	Launched Version: fabric-loader-0.11.1-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13587 Compatibility Profile Context 19.40.36.04 26.20.14036.4002, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, file/Charm4Faithful (incompatible), file/1.17 BlackGraniteFinalRedo (incompatible), file/Fences+.zip, file/Fences_-_Faithful_Addon.zip, file/Vertical Slabs by ksym_.zip (incompatible), file/Round-Trees-5.0-�31.16.2+�o.zip, file/Better-Leaves-4.0-�31.16.2+�o.zip, file/Circular Sun and Moon.zip (incompatible), file/Better Observers.zip (incompatible), file/Mine Progress Bar.zip (incompatible), file/Pebble-less Dirt in Faithful 1.15.zip (incompatible), file/VanillaTweaks_r944846.zip, file/FaithfulClearVisionGlass.zip (incompatible), file/shulker.zip, file/pot.zip, file/william-wythers-better-cacti.zip, file/baguette-addon.zip (incompatible), file/semiirontorches-v1.zip, file/icy-water-buckets.zip, file/hot-bucket.zip, file/Clean Redstone (incompatible), file/3D+Byg+V2.1.zip, file/Compliance_Transparent_GUI_release_1.1.zip, file/Glass+Doors+Addon+for+Faithful.zip (incompatible), file/Redstone+tools.zip (incompatible), file/RedstoneTweaks_v1.1.zip (incompatible), file/Redstone Utility Pack (incompatible), file/1.17 (1).zip (incompatible), file/OreGrids-Faithful.zip (incompatible), file/8_Silly_Minecraft_Features_Resourcepack.zip
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx 
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\Clement\AppData\Roaming\.minecraft\crash-reports\crash-2021-02-25_19.00.32-client.txt
AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by comp500** [comment]
See https://github.com/CaffeineMC/sodium-fabric/issues/16
