### ISSUE TITLE
indium crashing when placing a block from create

### ISSUE THREAD

**Issue by C41nn** [comp500/Indium#265]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-12-17 18:23:23
Description: Unexpected error

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.NonTerrainBlockRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.simibubi.create.content.kinetics.simpleRelays.BracketedKineticBlockModel.emitBlockQuads(BracketedKineticBlockModel.java:50)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.jozufozu.flywheel.fabric.model.DefaultLayerFilteringBakedModel.emitBlockQuads(DefaultLayerFilteringBakedModel.java:34)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.FixedLightBakedModel.emitBlockQuads(FixedLightBakedModel.java:40)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.TranslucentBakedModel.emitBlockQuads(TranslucentBakedModel.java:43)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:70)
	at net.minecraft.class_778.handler$cip000$indium$hookRender(class_778.java:1053)
	at net.minecraft.class_778.method_3374(class_778.java)
	at com.simibubi.create.foundation.utility.ghost.GhostBlockRenderer$TransparentGhostBlockRenderer.render(GhostBlockRenderer.java:96)
	at com.simibubi.create.foundation.utility.ghost.GhostBlocks.lambda$renderAll$2(GhostBlocks.java:61)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.simibubi.create.foundation.utility.ghost.GhostBlocks.renderAll(GhostBlocks.java:59)
	at com.simibubi.create.foundation.events.ClientEvents.onRenderWorld(ClientEvents.java:246)
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$22(WorldRenderEvents.java:222)
	at net.minecraft.class_761.handler$cek000$fabric-rendering-v1$beforeClouds(class_761.java:6065)
	at net.minecraft.class_761.method_22710(class_761.java:1509)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.simibubi.create.content.kinetics.simpleRelays.BracketedKineticBlockModel.emitBlockQuads(BracketedKineticBlockModel.java:50)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.jozufozu.flywheel.fabric.model.DefaultLayerFilteringBakedModel.emitBlockQuads(DefaultLayerFilteringBakedModel.java:34)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.FixedLightBakedModel.emitBlockQuads(FixedLightBakedModel.java:40)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at io.github.fabricators_of_create.porting_lib.models.virtual.TranslucentBakedModel.emitBlockQuads(TranslucentBakedModel.java:43)
	at link.infra.indium.renderer.render.NonTerrainBlockRenderContext.render(NonTerrainBlockRenderContext.java:70)
	at net.minecraft.class_778.handler$cip000$indium$hookRender(class_778.java:1053)
	at net.minecraft.class_778.method_3374(class_778.java)
	at com.simibubi.create.foundation.utility.ghost.GhostBlockRenderer$TransparentGhostBlockRenderer.render(GhostBlockRenderer.java:96)
	at com.simibubi.create.foundation.utility.ghost.GhostBlocks.lambda$renderAll$2(GhostBlocks.java:61)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at com.simibubi.create.foundation.utility.ghost.GhostBlocks.renderAll(GhostBlocks.java:59)
	at com.simibubi.create.foundation.events.ClientEvents.onRenderWorld(ClientEvents.java:246)
	at net.fabricmc.fabric.api.client.rendering.v1.WorldRenderEvents.lambda$static$22(WorldRenderEvents.java:222)
	at net.minecraft.class_761.handler$cek000$fabric-rendering-v1$beforeClouds(class_761.java:6065)
	at net.minecraft.class_761.method_22710(class_761.java:1509)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['qwiker'/157, l='ClientLevel', x=231.50, y=89.00, z=-246.50]]
	Chunk stats: 1024, 644
	Level dimension: minecraft:overworld
	Level spawn location: World: (224,76,-240), Section: (at 0,12,0 in 14,4,-15; chunk contains blocks 224,-64,-240 to 239,319,-225), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 376 game time, 376 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 138766352 bytes (132 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5700U with Radeon Graphics         
	Identifier: AuthenticAMD Family 23 Model 104 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 1.80
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: AMD Radeon(TM) Graphics
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 512.00
	Graphics card #0 deviceId: 0x164c
	Graphics card #0 versionInfo: DriverVersion=31.0.21024.5
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 17270.27
	Virtual memory used (MB): 15531.53
	Swap memory total (MB): 1550.02
	Swap memory used (MB): 185.02
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		ae2: Applied Energistics 2 15.0.15
			team_reborn_energy: Energy 3.0.0
		architectury: Architectury 9.1.12
		badpackets: Bad Packets 0.4.3
		balm-fabric: Balm 7.2.1
		bclib: BCLib 3.0.13
			wunderlib: WunderLib 1.1.5
		bettercombat: Better Combat 1.8.3+1.20.1
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0
		betterend: Better End 4.0.10
		betternether: Better Nether 9.0.9
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.7.4-1.20.1
			maelstrom_library: Maelstrom Library 1.6.1-1.20
			multipart_entities: MultipartEntities 1.5-1.20
		cardinal-components: Cardinal Components API 5.2.2
			cardinal-components-base: Cardinal Components API (base) 5.2.2
			cardinal-components-block: Cardinal Components API (blocks) 5.2.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.2.2
			cardinal-components-entity: Cardinal Components API (entities) 5.2.2
			cardinal-components-item: Cardinal Components API (items) 5.2.2
			cardinal-components-level: Cardinal Components API (world saves) 5.2.2
			cardinal-components-scoreboard: Cardinal Components API (scoreboard) 5.2.2
			cardinal-components-world: Cardinal Components API (worlds) 5.2.2
		chunkpregen: Fabric Chunk Pregenerator 0.3.3
		cloth-config: Cloth Config v11 11.1.106
			cloth-basic-math: cloth-basic-math 0.6.1
		create: Create 0.5.1-d-build.1161+mc1.20.1
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			flywheel: Flywheel 0.6.9-1
			forgeconfigapiport: Forge Config API Port 8.0.0
			milk: Milk Lib 1.2.60
				dripstone_fluid_lib: Dripstone Fluid Lib 3.0.2
			porting_lib_accessors: Porting Lib Accessors 2.1.1127+1.20
			porting_lib_base: Porting Lib Base 2.1.1127+1.20
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.1127+1.20
				porting_lib_utility: Porting Lib Utility 2.1.1127+1.20
			porting_lib_brewing: Porting Lib Brewing 2.1.1127+1.20
			porting_lib_client_events: Porting Lib Client Events 2.1.1127+1.20
				porting_lib_core: Porting Lib Core 2.1.1127+1.20
				porting_lib_gametest: Porting Lib GameTest 2.1.1127+1.20
			porting_lib_entity: Porting Lib Entity 2.1.1127+1.20
				porting_lib_mixin_extensions: Porting Lib Mixin Extensions 2.1.1127+1.20
			porting_lib_extensions: Porting Lib Extensions 2.1.1127+1.20
				porting_lib_attributes: Porting Lib Attributes 2.1.1127+1.20
				porting_lib_common: Porting Lib Common 2.1.1127+1.20
			porting_lib_fake_players: Porting Lib Fake Players 2.1.1127+1.20
			porting_lib_models: Porting Lib Models 2.1.1127+1.20
				porting_lib_model_loader: Porting Lib Model Loader 2.1.1127+1.20
			porting_lib_networking: Porting Lib Networking 2.1.1127+1.20
			porting_lib_obj_loader: Porting Lib Obj Loader 2.1.1127+1.20
			porting_lib_tags: Porting Lib Tags 3.0
			porting_lib_tool_actions: Porting Lib Tool Actions 2.1.1127+1.20
			porting_lib_transfer: Porting Lib Transfer 2.1.1127+1.20
			reach-entity-attributes: Reach Entity Attributes 2.4.0
			registrate-fabric: Registrate for Fabric 1.3.62-MC1.20.1
				porting_lib_data: Porting Lib Data 2.1.1090+1.20
				porting_lib_model_generators: Porting Lib Model Generators 2.1.1090+1.20
					porting_lib_model_materials: Porting Lib Model Materials 2.1.1090+1.20
		expandeddelight: Expanded Delight 0.3.0.2
		fabric-api: Fabric API 0.91.0+1.20.1
			fabric-api-base: Fabric API Base 0.4.30+7abfd51577
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.35+4d8536c977
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.12+215bbe9677
			fabric-block-api-v1: Fabric Block API (v1) 1.0.10+92a0d36777
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.0+92a0d36777
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.40+b3afc78b77
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.1+97bb207577
			fabric-command-api-v1: Fabric Command API (v1) 1.2.33+f71b366f77
			fabric-command-api-v2: Fabric Command API (v2) 2.2.12+b3afc78b77
			fabric-commands-v0: Fabric Commands (v0) 0.2.50+df3654b377
			fabric-containers-v0: Fabric Containers (v0) 0.1.63+df3654b377
			fabric-content-registries-v0: Fabric Content Registries (v0) 4.0.10+57aed33f77
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.4+a1a980da77
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.18+aeb40ebe77
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 12.3.3+d7b148e077
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.53+8536527b77
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.22+b3afc78b77
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.6.1+e91849a877
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.62+df3654b377
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.39+ae9f657a77
			fabric-item-api-v1: Fabric Item API (v1) 2.1.27+b3afc78b77
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.11+d7b148e077
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.36+fb8d95da77
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.34+df3654b377
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.21+b3afc78b77
			fabric-loot-api-v2: Fabric Loot API (v2) 1.2.0+96dfa95977
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.44+9e7660c677
			fabric-message-api-v1: Fabric Message API (v1) 5.1.8+d7b148e077
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.49+b3afc78b77
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.2+709a987177
			fabric-models-v0: Fabric Models (v0) 0.4.1+9386d8a777
			fabric-networking-api-v1: Fabric Networking API (v1) 1.3.10+eeb8eb3677
			fabric-networking-v0: Fabric Networking (v0) 0.3.50+df3654b377
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 11.1.2+4ee0bc6077
			fabric-particles-v1: Fabric Particles (v1) 1.1.1+201a23a077
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.20+b3afc78b77
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.3.2+4df89eb277
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.0+39a511ba77
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.0+39a511ba77
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.45+df3654b377
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.36+92a0d36777
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.27+b3afc78b77
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.48+df3654b377
			fabric-rendering-v1: Fabric Rendering (v1) 3.0.7+b3afc78b77
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.7+29de845d77
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.9+132c48c177
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.7+b3afc78b77
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.29+b3afc78b77
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.12+b3afc78b77
			fabric-transfer-api-v1: Fabric Transfer API (v1) 3.3.3+c81d263177
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 4.3.0+6c31357e77
		fabric-language-kotlin: Fabric Language Kotlin 1.10.16+kotlin.1.9.21
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.21
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.21
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.7.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.7.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.2
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.2
		fabricloader: Fabric Loader 0.14.25
		fabrictailor: Fabric Tailor 2.1.2
			config2brigadier: Config to Brigadier 1.2.3
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
		farmersdelight: Farmer's Delight 1.20.1-1.4.1
		geckolib: GeckoLib 4 4.3.1
			com_eliotlash_mclib_mclib: mclib 20
		gravestones: Gravestones v1.15
		indium: Indium 1.0.18+mc1.20
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.3
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lazydfu: LazyDFU 0.1.3
		lightmanscurrency: Lightman's Currency 1.20.1-1.0.1.1
		lithium: Lithium 0.11.2
		medievalorigins: Medieval Origins Revival 5.2.1+1.20.1
			additionalentityattributes: Additional Entity Attributes 1.4.0+1.20.0
			common-protection-api: Common Protection API 1.0.0
		minecraft: Minecraft 1.20.1
		modmenu: Mod Menu 7.2.2
		mr_dungeons_andtaverns: Dungeons and Taverns 3.0.1
		naturalist: Naturalist 4.0.3
		origins: Origins 1.10.0
			apoli: Apoli 2.9.0
				calio: Calio 1.11.0
				playerabilitylib: Pal 1.8.0
		origins-classes: Origins: Classes 1.7.0
		pehkui: Pehkui 3.7.11+1.14.4-1.20.2
			kanos_config: Kanos Config 0.4.1+1.14.4-1.19.4
		player-animator: Player Animator 1.0.2-rc1+1.20
		puffish_skills: Pufferfish's Skills 0.10.0
		railways: Create: Steam 'n' Rails 1.5.1+fabric-mc1.20.1
			mm: Manningham Mills 2.3
		simplyswords: Simply Swords 1.51.5-1.20.1
			spruceui: SpruceUI 5.0.0+1.20
		sliceanddice: Create Slice & Dice 3.0.0
		sodium: Sodium 0.4.10+build.27
		spell_engine: Spell Engine 0.12.4+1.20.1
			com_github_zsoltmolnarrr_tinyconfig: TinyConfig 2.3.2
		spell_power: Spell Power Attribute 0.9.19+1.20.1
		terrablender: TerraBlender 3.0.0.169
			com_electronwill_night-config_core: core 3.6.4
			com_electronwill_night-config_toml: toml 3.6.4
		terralith: Terralith 2.4.11
		travelersbackpack: Traveler's Backpack 1.20.1-9.1.8
		trinkets: Trinkets 3.7.1
		vcinteraction: Voice Chat Interaction 1.20.1-1.0.5
			polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.5.0+1.20
		voicechat: Simple Voice Chat 1.20.1-2.4.32
		waystones: Waystones 14.1.2
		woods_and_mires: Woods and Mires 2.1.1+1.20.1
			com_typesafe_config: config 1.4.2
		wthit: wthit 8.4.3
	Flywheel Backend: GL33 Instanced Arrays
	Launched Version: fabric-loader-0.14.25-1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: AMD Radeon(TM) Graphics GL version 3.2.0 Core Profile Context 23.10.24.230718, ATI Technologies Inc.
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric
	Current Language: en_us
	CPU: 16x AMD Ryzen 7 5700U with Radeon Graphics 
	Server Running: true
	Player Count: 1 / 8; [class_3222['qwiker'/157, l='ServerLevel[New World]', x=231.50, y=89.00, z=-246.50]]
	Data Packs: vanilla, fabric, medievalorigins:tag_loader
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by Poopooracoocoo** [comment]
![image](https://github.com/comp500/Indium/assets/51363864/6b8b2b4a-ef54-4b7c-ae70-7e4ae809b12e)
Get Fabric API 0.88.1
