### ISSUE TITLE
[Fabric-0.15.6-1.20.1] Crash with Continuity when entering a single world or server  

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [comp500/Indium#269]
# Modlist
[10:42:56] [main/INFO]: Loading 217 mods:
	- advancementinfo 1.20-fabric0.83.0-1.4
	- advancementplaques 1.4.11
	- allmusic_client 2.6.10
	   \-- org_gagravarr_vorbis-java-core 0.8
	- ambientsounds 5.3.0
	- animatica 0.6+1.20
	- architectury 9.1.12
	- autofish 0.9.10-SNAPSHOT
	- balm-fabric 7.1.4
	- betterclouds 1.3.13+1.20.1
	- bettermounthud 1.2.2
	- betterpingdisplay 1.1.1
	- betterthirdperson 1.9.0
	- borderlessmining 1.1.8+1.20.1
	- capes 1.5.2+1.20
	- carpet 1.4.112+v230608
	- chat_heads 0.10.27
	- chatpatches 201.5.5
	- chunksfadein 1.0.4-1.20.1
	   |-- com_moandjiezana_toml_toml4j 0.7.2
	   \-- crowdin-translate 1.4+1.19.3
	- citresewn 1.1.3+1.20
	   \-- citresewn-defaults 1.1.3+1.20
	- classicandsimplestatusbars 1.0.11
	- cloth-config 11.1.106
	   \-- cloth-basic-math 0.6.1
	- continuity 3.0.0-beta.4+1.20.1
	- controlify 1.6.0+1.20
	   |-- dev_isxander_sdl2-jni 2.28.2-26
	   |-- org_hid4java_hid4java 0.7.0
	   \-- org_quiltmc_quilt-json5 1.0.3
	- craftingtweaks 18.2.1
	- crawl 0.12.0
	   \-- mm 2.3
	- creativecore 2.11.9
	   \-- net_minecraftforge_eventbus 6.0.3
	- cupboard 1.20.1-2.1
	- debugify 1.20.1+2.0
	- disc_jockey 1.2.5
	- dynamic_fps 3.2.1
	- e4mc_minecraft 4.0.1
	- eatinganimationid 1.20+1.9.5-CMDfix
	- enhancedblockentities 0.9+1.20
	   |-- advanced_runtime_resource_pack 0.6.7
	   \-- spruceui 5.0.0+1.20
	- entity_model_features 1.0.2
	- entity_texture_features 4.5.1
	   \-- org_apache_httpcomponents_httpmime 4.5.10
	- entityculling 1.6.2-mc1.20.1
	- explosiveenhancement 1.2.2-1.20.x
	- fabric-api 0.91.0+1.20.1
	   |-- fabric-api-base 0.4.30+7abfd51577
	   |-- fabric-api-lookup-api-v1 1.6.35+4d8536c977
	   |-- fabric-biome-api-v1 13.0.12+215bbe9677
	   |-- fabric-block-api-v1 1.0.10+92a0d36777
	   |-- fabric-block-view-api-v2 1.0.0+92a0d36777
	   |-- fabric-blockrenderlayer-v1 1.1.40+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.1.1+97bb207577
	   |-- fabric-command-api-v1 1.2.33+f71b366f77
	   |-- fabric-command-api-v2 2.2.12+b3afc78b77
	   |-- fabric-commands-v0 0.2.50+df3654b377
	   |-- fabric-containers-v0 0.1.63+df3654b377
	   |-- fabric-content-registries-v0 4.0.10+57aed33f77
	   |-- fabric-convention-tags-v1 1.5.4+a1a980da77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.3.3+d7b148e077
	   |-- fabric-dimensions-v1 2.1.53+8536527b77
	   |-- fabric-entity-events-v1 1.5.22+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.1+e91849a877
	   |-- fabric-events-lifecycle-v0 0.2.62+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.39+ae9f657a77
	   |-- fabric-item-api-v1 2.1.27+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.11+d7b148e077
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.21+b3afc78b77
	   |-- fabric-loot-api-v2 1.2.0+96dfa95977
	   |-- fabric-loot-tables-v1 1.1.44+9e7660c677
	   |-- fabric-message-api-v1 5.1.8+d7b148e077
	   |-- fabric-mining-level-api-v1 2.1.49+b3afc78b77
	   |-- fabric-model-loading-api-v1 1.0.2+709a987177
	   |-- fabric-models-v0 0.4.1+9386d8a777
	   |-- fabric-networking-api-v1 1.3.10+eeb8eb3677
	   |-- fabric-networking-v0 0.3.50+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.2+4ee0bc6077
	   |-- fabric-particles-v1 1.1.1+201a23a077
	   |-- fabric-recipe-api-v1 1.0.20+b3afc78b77
	   |-- fabric-registry-sync-v0 2.3.2+4df89eb277
	   |-- fabric-renderer-api-v1 3.2.0+39a511ba77
	   |-- fabric-renderer-indigo 1.5.0+39a511ba77
	   |-- fabric-renderer-registries-v1 3.2.45+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.36+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.27+b3afc78b77
	   |-- fabric-rendering-v0 1.1.48+df3654b377
	   |-- fabric-rendering-v1 3.0.7+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.7+29de845d77
	   |-- fabric-resource-loader-v0 0.11.9+132c48c177
	   |-- fabric-screen-api-v1 2.0.7+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.29+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.3.3+c81d263177
	   \-- fabric-transitive-access-wideners-v1 4.3.0+6c31357e77
	- fabric-language-kotlin 1.10.10+kotlin.1.9.10
	   |-- org_jetbrains_kotlin_kotlin-reflect 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.9.10
	   |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.9.10
	   |-- org_jetbrains_kotlinx_atomicfu-jvm 0.22.0
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.7.3
	   |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.6.0
	   |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.6.0
	   \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.6.0
	- fabricloader 0.15.6
	   \-- mixinextras 0.3.2
	- fabricskyboxes 0.7.3+mc1.20.1
	- fabrishot 1.10.0
	- fadeless 1.0.1
	- fallingleaves 1.15.4
	- fastquit 3.0.0+1.20+
	- ferritecore 6.0.0
	- firstperson 2.3.0
	- forgeconfigapiport 8.0.0
	- fpsreducer 1.20-2.5
	- fsb-interop 1.3.6+mc1.20.1-build.50
	- highlighter 1.1.6
	- i18nupdatemod 3.5.3
	- iceberg 1.1.15
	- immediatelyfast 1.2.6+1.20.2
	   \-- net_lenni0451_reflect 1.2.4
	- indium 1.0.27+mc1.20.1
	- inventoryhud 3.4.18
	- iris 1.6.10
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- isxander-main-menu-credits 1.1.2
	- itemborders 1.2.0
	- itemscroller 0.20.0
	- jade 11.6.2
	- jadeaddons 5.2.3
	- java 17
	- lambdynlights 2.3.2+1.20.1
	   |-- pride 1.2.0+1.19.4
	   \-- spruceui 5.0.0+1.20
	- languagereload 1.5.9+1.20.1
	- litematica 0.15.3
	- lithium 0.11.2
	- malilib 0.16.3
	- memoryleakfix 1.1.2
	- minecraft 1.20.1
	- mixintrace 1.1.1+1.17
	- modelfix 1.14
	- modernfix 5.8.1+mc1.20.1
	- modmenu 7.2.2
	- moreculling 1.20.1-0.19.0
	   \-- conditional-mixin 0.3.2
	- mousewheelie 1.13.0+mc1.20.1
	   |-- amecsapi 1.5.1+mc1.20-pre1
	   |-- coat 1.0.0-beta.20+mc1.20-pre1
	   |-- tweed4_annotated 1.3.1+mc1.20-pre1
	   |-- tweed4_base 1.7.1+mc1.20-pre1
	   |-- tweed4_data 1.2.1+mc1.20-pre1
	   |-- tweed4_data_hjson 1.1.1+mc1.20-pre1
	   |-- tweed4_tailor_coat 1.1.3+mc1.20-pre1
	   |-- tweed4_tailor_lang_json_descriptions 1.1.0+mc1.20-pre1
	   \-- tweed4_tailor_screen 1.1.4+mc1.20-pre1
	- nochatreports 1.20.1-v2.2.2
	- notenoughanimations 1.7.0
	- optigui 2.1.5
	   |-- optiglue 2.1.5-mc.1.19.3
	   |-- org_apache_commons_commons-text 1.10.0
	   \-- org_ini4j_ini4j 0.5.4
	- owo 0.11.2+1.20
	   \-- blue_endless_jankson 1.2.2
	- prism 1.0.5
	- puzzle 1.5.2+1.20
	   |-- midnightlib 1.4.1
	   |-- puzzle-base 1.5.2+1.20
	   |-- puzzle-gui 1.5.2+1.20
	   |-- puzzle-models 1.5.2+1.20
	   \-- puzzle-splashscreen 1.5.2+1.20
	- reeses-sodium-options 1.6.5+mc1.20.1-build.95
	- roughlyenoughitems 12.0.674
	   \-- error_notifier 1.0.9
	- roughlyenoughresources 2.9.0
	- rrls 3.2.0-1.20.1-fabric
	- shouldersurfing 2.7
	- skinlayers 1.5.4-mc1.20.1
	- sodium 0.5.3
	- sodium-extra 0.5.1+mc1.20.1-build.112
	   |-- caffeineconfig 1.3.0+1.17
	   \-- crowdin-translate 1.4+1.19.3
	- telepistons 1.1.3
	- trajectory-preview 3.3-1.20.1
	- tweakeroo 0.17.1
	- visuality 0.7.1+1.20
	- voicechat 1.20.1-2.4.28
	- wildfire_gender 1.20-3.0.1
	- xaerominimap 23.8.4
	- xaeroworldmap 1.36.0
	- yet_another_config_lib_v3 3.2.1+1.20
	   |-- com_twelvemonkeys_common_common-image 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-io 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_common_common-lang 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-core 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-metadata 3.10.0-SNAPSHOT
	   |-- com_twelvemonkeys_imageio_imageio-webp 3.10.0-SNAPSHOT
	   |-- org_quiltmc_parsers_gson 0.2.1
	   \-- org_quiltmc_parsers_json 0.2.1
	- yosbr 0.1.2
	- yungsapi 1.20-Fabric-4.0.2
	   |-- org_javassist_javassist 3.29.2-GA
	   \-- org_reflections_reflections 0.10.2
	- zoomify 2.11.2
	   |-- com_akuleshov7_ktoml-core-jvm 0.4.1
	   |-- dev_isxander_settxi_settxi-core 2.10.6
	   \-- dev_isxander_settxi_settxi-kotlinx-serialization 2.10.6
# Log
[00:44:29] [Chunk Render Task Executor #0/ERROR]: Chunk build failed
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transformOnce(CTMBakedModel.java:112) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transform(CTMBakedModel.java:102) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:63) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:111) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:74) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[indium-1.0.27+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.27+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cpj000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	... 4 more
[10:44:29] [Render thread/INFO]: [ChatLog.serialize] Saved the chat log containing 2 messages and 0 sent messages to 'D:\Minecraft\1.20Fabric音乐\versions\1.20.1-0.15.6-fabric\logs\chatlog.json'
[10:44:29] [Render thread/INFO]: [voicechat] Clearing audio channels
[10:44:29] [Render thread/INFO]: Minimap session finalized.
[10:44:29] [Render thread/INFO]: Finalizing world map session...
[10:44:29] [Thread-25/INFO]: World map force-cleaned!
[10:44:29] [Render thread/INFO]: World map session finalized.
[10:44:29] [Render thread/INFO]: Stopping worker threads
[10:44:29] [Render thread/INFO]: emissive suffixes loaded: {_e}
[10:44:29] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Tessellating block in world - Indium Renderer
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.fillCrashInfo(ChunkBuilderMeshingTask.java:168) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:132) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:39) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:44) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:186) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.fabricmc.fabric.api.renderer.v1.model.SpriteFinder.find(net.fabricmc.fabric.api.renderer.v1.mesh.QuadView)" because the return value of "me.pepperbell.continuity.client.util.RenderUtil.getSpriteFinder()" is null
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transformOnce(CTMBakedModel.java:112) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel$CTMQuadTransform.transform(CTMBakedModel.java:102) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractRenderContext.transform(AbstractRenderContext.java:63) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext.renderQuad(AbstractBlockRenderContext.java:111) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.render.AbstractBlockRenderContext$2.emitDirectly(AbstractBlockRenderContext.java:74) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:261) ~[indium-1.0.27+mc1.20.1.jar:?]
	at link.infra.indium.renderer.mesh.MutableQuadViewImpl.emit(MutableQuadViewImpl.java:56) ~[indium-1.0.27+mc1.20.1.jar:?]
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:65) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at net.minecraft.class_1087.emitBlockQuads(class_1087.java:1039) ~[client-intermediary.jar:?]
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51) ~[fabric-renderer-api-v1-3.2.0+39a511ba77-b424792037380777.jar:?]
	at me.pepperbell.continuity.client.model.CTMBakedModel.emitBlockQuads(CTMBakedModel.java:53) ~[continuity-3.0.0-beta.4+1.20.1.jar:?]
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131) ~[indium-1.0.27+mc1.20.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$cpj000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:543) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:103) ~[sodium-fabric-mc1.20.1-0.5.3.jar:?]
	... 4 more
[10:44:29] [Render thread/INFO]: [FastQuit] Exiting FastQuit.

**Comment by comp500** [comment]
Could you try to replicate this issue with fewer mods? I don't know why this would occur, though I think it's more likely to be a Continuity issue than an Indium one.

**Comment by Sorrow-Scarlet** [comment]
I'll try if i can find time to do it :)

**Comment by VindSole** [comment]
Seems fixed on my end.

**Comment by comp500** [comment]
Closing: it's been a while since this was reported - likely to be resolved now?
