### ISSUE TITLE
Version 1.0.30 does not work for 1.20.1

### ISSUE THREAD

**Issue by MagicznyNikt560** [comp500/Indium#298]
Game does not open and does not create a crash report nor a fabric error window
![Zrzut ekranu 2024-06-09 121157](https://github.com/comp500/Indium/assets/172180001/09443d18-d6e2-4132-91e1-49151488ee2b)
here is a list of mods I use
![Zrzut ekranu 2024-06-09 121225](https://github.com/comp500/Indium/assets/172180001/073a0476-0be8-4355-bdd2-6dcc3d4623d5)
I tried pulling out mods and different versions of them and came to conclusion that indium couses the problem
I also tried an older version of indium that supports 1.20.1 and this time fabric showed an error
![Zrzut ekranu 2024-06-09 121939](https://github.com/comp500/Indium/assets/172180001/8d0f3646-7a83-40dd-ba0f-34829a6c3d0a)
but this error is to be expected

**Comment by comp500** [comment]
Could you upload the `latest.log` file in the logs folder? Or a crash report in the `crash-reports` folder? I don't have enough information here to diagnose the issue. Please make sure all your mods are up to date!

**Comment by MagicznyNikt560** [comment]
[20:06:58] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.11
[20:06:58] [main/INFO]: Loading 76 mods:
	- betterf3 7.0.1
	   \-- cloth-config 11.1.106
	        \-- cloth-basic-math 0.6.1
	- distanthorizons 2.1.0-a
	- fabric-api 0.92.2+1.20.1
	   |-- fabric-api-base 0.4.31+1802ada577
	   |-- fabric-api-lookup-api-v1 1.6.36+1802ada577
	   |-- fabric-biome-api-v1 13.0.13+1802ada577
	   |-- fabric-block-api-v1 1.0.11+1802ada577
	   |-- fabric-block-view-api-v2 1.0.1+1802ada577
	   |-- fabric-blockrenderlayer-v1 1.1.41+1802ada577
	   |-- fabric-client-tags-api-v1 1.1.2+1802ada577
	   |-- fabric-command-api-v1 1.2.34+f71b366f77
	   |-- fabric-command-api-v2 2.2.13+1802ada577
	   |-- fabric-commands-v0 0.2.51+df3654b377
	   |-- fabric-containers-v0 0.1.64+df3654b377
	   |-- fabric-content-registries-v0 4.0.11+1802ada577
	   |-- fabric-convention-tags-v1 1.5.5+1802ada577
	   |-- fabric-crash-report-info-v1 0.2.19+1802ada577
	   |-- fabric-data-attachment-api-v1 1.0.0+de0fd6d177
	   |-- fabric-data-generation-api-v1 12.3.4+1802ada577
	   |-- fabric-dimensions-v1 2.1.54+1802ada577
	   |-- fabric-entity-events-v1 1.6.0+1c78457f77
	   |-- fabric-events-interaction-v0 0.6.2+1802ada577
	   |-- fabric-events-lifecycle-v0 0.2.63+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.40+1802ada577
	   |-- fabric-item-api-v1 2.1.28+1802ada577
	   |-- fabric-item-group-api-v1 4.0.12+1802ada577
	   |-- fabric-key-binding-api-v1 1.0.37+1802ada577
	   |-- fabric-keybindings-v0 0.2.35+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.22+1802ada577
	   |-- fabric-loot-api-v2 1.2.1+1802ada577
	   |-- fabric-loot-tables-v1 1.1.45+9e7660c677
	   |-- fabric-message-api-v1 5.1.9+1802ada577
	   |-- fabric-mining-level-api-v1 2.1.50+1802ada577
	   |-- fabric-model-loading-api-v1 1.0.3+1802ada577
	   |-- fabric-models-v0 0.4.2+9386d8a777
	   |-- fabric-networking-api-v1 1.3.11+1802ada577
	   |-- fabric-networking-v0 0.3.51+df3654b377
	   |-- fabric-object-builder-api-v1 11.1.3+1802ada577
	   |-- fabric-particles-v1 1.1.2+1802ada577
	   |-- fabric-recipe-api-v1 1.0.21+1802ada577
	   |-- fabric-registry-sync-v0 2.3.3+1802ada577
	   |-- fabric-renderer-api-v1 3.2.1+1802ada577
	   |-- fabric-renderer-indigo 1.5.2+85287f9f77
	   |-- fabric-renderer-registries-v1 3.2.46+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.37+92a0d36777
	   |-- fabric-rendering-fluids-v1 3.0.28+1802ada577
	   |-- fabric-rendering-v0 1.1.49+df3654b377
	   |-- fabric-rendering-v1 3.0.8+1802ada577
	   |-- fabric-resource-conditions-api-v1 2.3.8+1802ada577
	   |-- fabric-resource-loader-v0 0.11.10+1802ada577
	   |-- fabric-screen-api-v1 2.0.8+1802ada577
	   |-- fabric-screen-handler-api-v1 1.3.30+1802ada577
	   |-- fabric-sound-api-v1 1.0.13+1802ada577
	   |-- fabric-transfer-api-v1 3.3.5+8dd72ea377
	   \-- fabric-transitive-access-wideners-v1 4.3.1+1802ada577
	- fabricloader 0.15.11
	   \-- mixinextras 0.3.5
	- ferritecore 6.0.1
	- fps 1.20-1.3.0-Fabric
	- immediatelyfast 1.2.1+1.20.1
	   \-- net_lenni0451_reflect 1.2.1
	- indium 1.0.30+mc1.20.4
	- iris 1.7.0+mc1.20.1
	   |-- io_github_douira_glsl-transformer 2.0.0-pre13
	   |-- org_anarres_jcpp 1.4.14
	   \-- org_antlr_antlr4-runtime 4.11.1
	- java 17
	- lazydfu 0.1.3
	- lithium 0.11.2
	- minecraft 1.20.1
	- modmenu 7.2.1
	- nvidium 0.2.6-beta
	- sodium 0.5.8+mc1.20.1
	- starlight 1.1.2+fabric.dbc156f
[20:07:01] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/PC/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.13.3+mixin.0.8.5/sponge-mixin-0.13.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:07:02] [main/INFO]: Compatibility level set to JAVA_17
[20:07:02] [main/INFO]: Loaded configuration file for Lithium: 115 options available, 1 override(s) found
[20:07:02] [main/INFO]: Loaded configuration file for Sodium: 42 options available, 3 override(s) found
[20:07:02] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.entity.CuboidMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.entity.ModelPartMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.entity.cull.EntityRendererMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.entity.shadows.EntityRenderDispatcherMixin' as rule 'mixin.features.render.entity' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.gui.font.GlyphRendererMixin' as rule 'mixin.features.render.gui.font' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.world.sky.BackgroundRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.world.sky.ClientWorldMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[20:07:02] [main/WARN]: Force-disabling mixin 'features.render.world.sky.WorldRendererMixin' as rule 'mixin.features.render.world.sky' (added by mods [iris]) disables it and children
[20:07:03] [main/INFO]: Searching for graphics cards...
[20:07:03] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.5).
[20:07:03] [main/INFO]: Found graphics card: GraphicsAdapterInfo[vendor=NVIDIA, name=NVIDIA GeForce RTX 2060, version=DriverVersion=31.0.15.4617]
[20:07:03] [main/WARN]: Sodium has applied one or more workarounds to prevent crashes or other issues on your system: [NVIDIA_THREADED_OPTIMIZATIONS]
[20:07:03] [main/WARN]: This is not necessarily an issue, but it may result in certain features or optimizations being disabled. You can sometimes fix these issues by upgrading your graphics driver.
[20:07:09] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:07:09] [Render thread/INFO]: Setting user: Magiczny_Nikt560
[20:07:09] [Render thread/INFO]: [BetterF3] Loading...
[20:07:09] [Render thread/INFO]: [BetterF3] All done!
[20:07:09] [Render thread/INFO]: Initializing Distant Horizons
[20:07:10] [Render thread/INFO]: Java.awt.headless set to true. Distant Horizons can correctly display error and info dialog windows.
[20:07:10] [Render thread/INFO]: Distant Horizons, Version: 2.1.0-a
[20:07:10] [Render thread/INFO]: DH Branch: main
[20:07:10] [Render thread/INFO]: DH Commit: 71ca26bba99dcd41e82cb08dc12f44d0f0aa5011
[20:07:10] [Render thread/INFO]: DH Jar Build Source: User
[20:07:10] [Render thread/INFO]: Registering Fabric Client Events
[20:07:10] [Render thread/INFO]: Registering Fabric Server Events
[20:07:10] [Render thread/INFO]: Registered mod compatibility accessor for: [Sodium-Fabric].
[20:07:10] [Render thread/INFO]: Registered mod compatibility accessor for: [Starlight-Fabric-1.18.X].
[20:07:10] [Render thread/INFO]: Registered mod compatibility accessor for: [iris].
[20:07:10] [Render thread/INFO]: Distant Horizons Initialized
[20:07:10] [Render thread/INFO]: Initialising config for DistantHorizons
[20:07:10] [Render thread/INFO]: [STDOUT]: Type [class java.lang.Double] isn't a convertible value in the config file handler
[20:07:10] [Render thread/WARN]: Entry [client.advanced.graphics.advancedGraphics.overdrawPrevention] had an invalid value when loading the config. Using default value.
[20:07:10] [Render thread/WARN]: Entry [client.advanced.graphics.advancedGraphics.lodShading] had an invalid value when loading the config. Using default value.
[20:07:10] [Render thread/INFO]: Config for DistantHorizons initialised
[20:07:10] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[20:07:10] [Render thread/INFO]: Loading ImmediatelyFast 1.2.1+1.20.1
[20:07:10] [Render thread/INFO]: Found Iris 1.7.0+mc1.20.1. Enabling compatibility.
[20:07:10] [Render thread/ERROR]: Failed to initialize Iris compatibility. Try updating Iris and ImmediatelyFast before reporting this on GitHub
java.lang.ClassNotFoundException: net.coderbot.iris.vertices.ImmediateState
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.11.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at fabric.net.raphimc.immediatelyfast.compat.IrisCompat.init(IrisCompat.java:41) ~[ImmediatelyFast-1.2.1+1.20.1.jar:?]
	at fabric.net.raphimc.immediatelyfast.fabric.ImmediatelyFastFabric.lambda$onInitializeClient$0(ImmediatelyFastFabric.java:34) ~[ImmediatelyFast-1.2.1+1.20.1.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at fabric.net.raphimc.immediatelyfast.fabric.ImmediatelyFastFabric.onInitializeClient(ImmediatelyFastFabric.java:32) ~[ImmediatelyFast-1.2.1+1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[fabric-loader-0.15.11-1.20.1.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?]

**Comment by MagicznyNikt560** [comment]
Oh I'm sorry, I read the log just now and realised the problem, it was immedietly fast that I forgot to update
