### ISSUE TITLE
Version 1.0.31 does not work with latest version of Minecraft (1.20.6)

### ISSUE THREAD

**Issue by zman29er** [comp500/Indium#299]
Game does not open and crashes whenever attempting to load the Indium client. Tried the following with non-expected results:
- Downgrading the API version from latest  (0.100.0) to 0.99.4
- Removing certain mods affected by Indium (DistantHorizons)
- Downgrading Indium version (self-explanitory on what would happen)
<img width="424" alt="image" src="https://github.com/comp500/Indium/assets/171362424/45fa7626-0db9-459d-bdf7-db19347d877e">

**Comment by comp500** [comment]
Could you send the full crash report? This should be put in the `crash-reports` folder. The `logs/latest.log` file would also be helpful.

**Comment by TimPGamer** [comment]
If i start the game it just says that indium 1.0.31 isnt compatible with sodium 0.5.9, only with 0.5.8
also ignore, that indium says its 1.20.4 in the pic, cause it isnt, i just downloaded it from curseforge and its labled wrong.
![Screenshot 2024-06-16 210330](https://github.com/comp500/Indium/assets/129323516/e1048b19-aee4-4ced-9601-077ee90f0a33)

**Comment by Benzeel** [comment]
i also get this issue (the one in the comment above, but not a full crash like the original post), with both indium versions for 1.20.6

it says it requires an older build of sodium (even on modrinth) with 1.20.4
when you download the build of sodium it requests, it still throws the same error found in the screenshot in the comment above mine

**Comment by Benzeel** [comment]
here is the latest log:

[15:33:18] [main/INFO]: Loading Minecraft 1.20.6 with Fabric Loader 0.15.11
[15:33:18] [ForkJoinPool-1-worker-7/WARN]: Mod com_github_fallen-breath_conditional-mixin uses the version v0.6.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'v0'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[15:33:18] [main/WARN]: Mod resolution failed
[15:33:19] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE indium 1.0.31+mc1.20.4 {depends sodium @ [0.5.8]}, ROOT_FORCELOAD_SINGLE indium 1.0.31+mc1.20.4]
[15:33:19] [main/INFO]: Reason: [HARD_DEP indium 1.0.31+mc1.20.4 {depends sodium @ [0.5.8]}]
[15:33:19] [main/INFO]: Fix: add [], remove [], replace [[sodium 0.5.9+mc1.20.6] -> add:sodium 0.5.9 ([[0.5.9,0.5.9]]), [indium 1.0.31+mc1.20.4] -> add:indium 1 ([(-∞,∞)])]
[15:33:19] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Sodium' (sodium) 0.5.9+mc1.20.6 with version 0.5.9 that is compatible with:
		 - indium, any version
	 - Replace mod 'Indium' (indium) 1.0.31+mc1.20.4 with any version that is compatible with:
		 - sodium, version 0.5.9
More details:
	 - Mod 'Indium' (indium) 1.0.31+mc1.20.4 requires version 0.5.8 of mod 'Sodium' (sodium), but only the wrong version is present: 0.5.9+mc1.20.6!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

**Comment by Benzeel** [comment]
i have tried:
sodium 0.5.8 (1.20.6)
sodium 0.5.9 (1.20.6)
sodium 0.5.8 (1.20.4)

![image](https://limey-is.me/DGrqL6CrkcT2/direct)
![image](https://limey-is.me/hB3zwJg0vUIU/direct)
![image](https://limey-is.me/beaqZaxNXhQf/direct)

**Comment by comp500** [comment]
@TimPGamer @Benzeel Neither of these are the same issue. Indium has now been released for Sodium 0.5.9/0.5.10, please update.

**Comment by comp500** [comment]
Closing: insufficient information to diagnose issue
