### ISSUE TITLE
Crashes when adding Hydrogen.

### ISSUE THREAD

**Issue by Pepe20129** [comp500/Indium#39]
The game crashes when adding [Hydrogen](https://cdn.modrinth.com/data/AZomiSrC/versions/mc1.16.5-v0.2.0/hydrogen-fabric-mc1.16.5-0.2.jar).

Mixin apply failed indium.mixins.json:sodium.MixinWorldSlice -> me.jellysquid.mods.sodium.client.world.WorldSlice: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method getLocalBlockIndex in indium.mixins.json:sodium.MixinWorldSlice was not located in the target class me.jellysquid.mods.sodium.client.world.WorldSlice. Using refmap indium-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method getLocalBlockIndex in indium.mixins.json:sodium.MixinWorldSlice was not located in the target class me.jellysquid.mods.sodium.client.world.WorldSlice. Using refmap indium-refmap.json
	at Not Enough Crashes deobfuscated stack trace.(1.16.3+build.47)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:423)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:399)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:286)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:264)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1272)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.<init>(ChunkRenderManager.java:92)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:248)
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.setWorld(SodiumWorldRenderer.java:108)
	at net.minecraft.client.render.WorldRenderer.handler$zzc000$onWorldChanged(WorldRenderer:3629)
	at net.minecraft.client.render.WorldRenderer.setWorld(WorldRenderer:744)
	at net.minecraft.client.MinecraftClient.setWorld(MinecraftClient:2049)
	at net.minecraft.client.MinecraftClient.joinWorld(MinecraftClient:1974)
	at net.minecraft.client.network.ClientPlayNetworkHandler.onGameJoin(ClientPlayNetworkHandler:382)
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:110)
	at net.minecraft.network.packet.s2c.play.GameJoinS2CPacket.apply(GameJoinS2CPacket:18)
	at net.minecraft.network.NetworkThreadUtils.method_11072(NetworkThreadUtils:21)
	at net.minecraft.class_2600$$Lambda$6748/2068494100.run(Unknown Source)
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:144)
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23)
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:118)
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:103)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1015)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:681)
	at net.minecraft.client.main.Main.main(Main:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

**Comment by comp500** [comment]
For Indium, you need to use the [1.16.x/next branch of Sodium](https://github.com/CaffeineMC/sodium-fabric#bleeding-edge-builds).
