### ISSUE TITLE
(Bits and Chisels) Crash as soon as I try chiselling a block

### ISSUE THREAD

**Issue by Schlungo** [comp500/Indium#75]
Hiya,

Hopefully someone is able to help me out here because I haven't got a clue what to do :')

Many thanks,

[18:43:11] [Render thread/FATAL]: Unreported exception thrown!
java.util.concurrent.CompletionException: net.minecraft.class_148: Tesselating block in world - Indium Renderer
	at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412) ~[?:?]
	at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2114) ~[?:?]
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.findNext(FutureQueueDrainingIterator.java:33) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.common.util.collections.FutureQueueDrainingIterator.hasNext(FutureQueueDrainingIterator.java:23) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.setupUploadBatches(RenderRegionManager.java:108) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.region.RenderRegionManager.upload(RenderRegionManager.java:29) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.RenderSectionManager.updateChunks(RenderSectionManager.java:407) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.updateChunks(SodiumWorldRenderer.java:222) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at net.minecraft.class_761.method_3273(class_761.java:11339) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_761.method_22710(class_761.java:1143) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3188(class_757.java:1001) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:806) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1114) ~[intermediary-1.17.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:730) [intermediary-1.17.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:217) [intermediary-1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153) [fabric-loader-0.11.6.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28) [fabric-loader-0.11.6.jar:?]
Caused by: net.minecraft.class_148: Tesselating block in world - Indium Renderer
	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:85) ~[indium-1.0.0+mc1.17.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$znm000$onRenderBlock(ChunkRenderRebuildTask.java:560) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:97) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
Caused by: java.lang.NoSuchMethodError: 'int me.jellysquid.mods.sodium.client.render.chunk.compile.buffers.ChunkModelBuilder.getChunkId()'
	at link.infra.indium.renderer.render.IndiumChunkRenderInfo.getInitializedBuffer(IndiumChunkRenderInfo.java:93) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractQuadRenderer.bufferQuad(AbstractQuadRenderer.java:76) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractQuadRenderer.tesselateSmooth(AbstractQuadRenderer.java:119) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractMeshConsumer.tesselateQuad(AbstractMeshConsumer.java:118) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractMeshConsumer.renderQuad(AbstractMeshConsumer.java:103) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractMeshConsumer.accept(AbstractMeshConsumer.java:78) ~[indium-1.0.0+mc1.17.1.jar:?]
	at link.infra.indium.renderer.render.AbstractMeshConsumer.accept(AbstractMeshConsumer.java:40) ~[indium-1.0.0+mc1.17.1.jar:?]
	at io.github.coolmineman.bitsandchisels.BitsBlockModel.emitBlockQuads(BitsBlockModel.java:46) ~[bitsandchisels-2.5.0.jar:?]
	at link.infra.indium.renderer.render.IndiumTerrainRenderContext.tesselateBlock(IndiumTerrainRenderContext.java:80) ~[indium-1.0.0+mc1.17.1.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.redirect$znm000$onRenderBlock(ChunkRenderRebuildTask.java:560) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:97) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:207) ~[b82cc88e-ace3-47e7-9d1e-7f40defcc764.jar:?]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
[18:43:12] [Server thread/INFO]: Stopping server

**Comment by comp500** [comment]
Your version of Sodium is outdated, please update to the 0.3.0 release or find the appropriate Indium development build for your version of Sodium. If you're using Iris, ask in the Iris support channels, they'll have the version of Indium you need.

**Comment by Schlungo** [comment]
thank you very much xx
