### ISSUE TITLE
Minecraft won't launch with indium and better end

### ISSUE THREAD

**Issue by topbun92** [comp500/Indium#80]
not even sure what the problem is. i manually removed every single mod to ensure that Indium, sodium, iris and fapi worked by themselves; they did. checked each individual mod in my pack against that control the only mod that produced the problem was better end. minecraft gets stuck at loading screen and loops infinitely 
![Iris_Indium bug screenshot](https://user-images.githubusercontent.com/87154955/128176967-079f8169-51fd-45f0-9eb2-b4848330e891.png)
[Iris_Indium bug.txt](https://github.com/comp500/Indium/files/6931014/Iris_Indium.bug.txt)

**Comment by topbun92** [comment]
should add, that iris/sodium without indium does not produce this error

**Comment by comp500** [comment]
This looks like an issue with CTMF, not Indium; see the stack trace of the crash:

```
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1617) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1615) ~[?:?]
	at team.chisel.ctm.client.handler.CTMModelsAddedCallbackHandler.onModelsAdded(CTMModelsAddedCallbackHandler.java:39) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at team.chisel.ctm.client.event.ModelsAddedCallback.lambda$static$0(ModelsAddedCallback.java:18) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at net.minecraft.class_1088.handler$bad000$onFinishAddingModels(class_1088.java:2116) ~[intermediary-minecraft-1.17.1-client.jar:?]
...
```
