### ISSUE TITLE
Infinite loading time when Indium is installed

### ISSUE THREAD

**Issue by remidu64** [comp500/Indium#81]
Whenever Indium is installed and i try to load the game, the loading bar just goes back and does that forever.
[Here](https://www.youtube.com/watch?v=E1XMEhje_MM) is a video of the game loading with Indium installed
the version used is 1.17 with fabric loader 0.11.6 if i remember correctly

**Comment by comp500** [comment]
Could you send the latest.log file in your logs folder?

**Comment by remidu64** [comment]
ok here it is
[latest.log](https://github.com/comp500/Indium/files/6954172/latest.log)
btw i just checked my fabric loader version and its 0.11.6

**Comment by MenacingPerson** [comment]
try removing inventoryhud

**Comment by comp500** [comment]
This looks like an issue with CTMF, not Indium; see the stack trace of the crash:

```
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1584) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1617) ~[?:?]
	at java.util.HashMap$EntryIterator.next(HashMap.java:1615) ~[?:?]
	at team.chisel.ctm.client.handler.CTMModelsAddedCallbackHandler.onModelsAdded(CTMModelsAddedCallbackHandler.java:39) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at team.chisel.ctm.client.event.ModelsAddedCallback.lambda$static$0(ModelsAddedCallback.java:18) ~[ctm-fabric-0.5.0+1.17.jar:?]
	at net.minecraft.class_1088.handler$bnb000$onFinishAddingModels(class_1088.java:2116) ~[intermediary-fabric-loader-0.11.6-1.17.jar:?]
...
```

**Comment by remidu64** [comment]
I removed the mod and now it works.
Thanks a lot !
