### ISSUE TITLE
can't run on m1 clip

### ISSUE THREAD

**Issue by juzijun233** [comp500/Indium#90]
net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-renderer-api-v1 0.3.0 (later versions might work too).
Unmet dependency listing:
	 - Mod 'Indium' (indium) requires "version 0.3.0 or later" of fabric-renderer-api-v1, which is missing!
Inactive mods:
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+a02b446313, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.7+b7ab612113, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:183)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:48)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:203)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:183)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:119)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by comp500** [comment]
Indium requires Fabric API, please install a recent version of it.
