### ISSUE TITLE
Missing fabric-renderer-api-v1

### ISSUE THREAD

**Issue by ccicnce113424** [comp500/Indium#98]
Minecraft version is 1.18.1. The latest versions of Sodium and Fabric API have been installed.
```
net.fabricmc.loader.impl.FormattedException: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-renderer-api-v1, version 0.3.0 or later.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.2-alpha1+mc1.18 requires version 0.3.0 or later of fabric-renderer-api-v1, which is missing!
Inactive mods:
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:189)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:142)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:71)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: net.fabricmc.loader.impl.discovery.ModResolutionException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-renderer-api-v1, version 0.3.0 or later.
Unmet dependency listing:
	 - Mod 'Indium' (indium) 1.0.2-alpha1+mc1.18 requires version 0.3.0 or later of fabric-renderer-api-v1, which is missing!
Inactive mods:
	 - mod 'Fabric API Base' (fabric-api-base) 0.3.0+c88702897d, reason: newer version active
	 - mod 'Fabric API Base' (fabric-api-base) 0.4.1+b4f4f6cd14, reason: newer version active
	 - mod 'Fabric Key Binding API (v1)' (fabric-key-binding-api-v1) 1.0.8+c8aba2f314, reason: newer version active
	 - mod 'Fabric Resource Loader (v0)' (fabric-resource-loader-v0) 0.4.11+3ac43d9514, reason: newer version active
	at net.fabricmc.loader.impl.discovery.ModResolver.findCompatibleSet(ModResolver.java:159)
	at net.fabricmc.loader.impl.discovery.ModResolver.resolve(ModResolver.java:45)
	at net.fabricmc.loader.impl.FabricLoaderImpl.setup(FabricLoaderImpl.java:224)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:187)
	... 3 more
```

**Comment by comp500** [comment]
What are the mods in your mods folder?

**Comment by ccicnce113424** [comment]
![image](https://user-images.githubusercontent.com/30774232/147869142-e8185b37-0cc7-4901-8cc6-21d381c3522c.png)

**Comment by ccicnce113424** [comment]
I installed Sodium and Fabric API first, and then installed Indium after launching the game. The problem did not reappear. But when I installed all mods at once and started the game for the first time, the problem recurred.
This may be a problem of the Fabric itself, and has nothing to do with Indium.
